image: docker:dind
variables:
  CI_REGISTRY_IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAME"

build-certbot:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  

test-py:
  stage: test
  script:
    - docker run --rm -t -v ${PWD}:/test --entrypoint="python" "$CI_REGISTRY_IMAGE" /test/test.py

test-sh:
  stage: test
  script:
    - docker run --rm -t -v ${PWD}:/test --entrypoint="/bin/sh" express-gateway /test/test.sh
    
deploy-master:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
