image: docker:dind
variables:
  CI_REGISTRY_IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAME"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test:
  stage: test
  image: python:3.7-alpine3.10
  before_script:
    - apk add --no-cache --virtual .build-deps gcc linux-headers openssl-dev musl-dev libffi-dev
    - pip install schedule pyOpenSSL
  script:
    - python test.py

deploy-master:
  stage: deploy
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
